import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/layouts/MainLayout";

export const metadata: Metadata = {
  title: "Mani Alipour",
  icons: ["/mani-alipour-logo.ico"],
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="bg-slate-950 text-white font-yekan">
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
