import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/layouts/MainLayout";

export const metadata: Metadata = {
  title: "Mani Alipour",
  icons: ["/mani-alipour-logo.ico"],
  description: "Generated by create next app",
  themeColor: [{ media: "(prefers-color-scheme: dark)", color: "#000000" }],
  other: {
    "color-scheme": "dark",
    "supported-color-schemes": "dark",
    "darkreader-lock": "",
    "force-color-adjust": "none",
  },
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body
        // Delete the bg-slate-950 which forces a flat color and
        // add a background gradient more consistent with the primary sections.
        className="bg-gradient-to-br from-cyan-950 via-slate-900 to-cyan-950 text-white font-yekan"
        style={{
          minHeight: "100dvh",
          // Make sure background applies to the full viewport and matches HeroSection
        }}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
